apiVersion: v1
kind: ConfigMap
metadata:
  name: ucrmp-config
  namespace: ucrmp-dev
data:
  # Global Config
  SPRING_PROFILES_ACTIVE: "dev" 
  SPRING_APPLICATION_JSON: '{"eureka": {"instance": {"prefer-ip-address": true}}}' # ðŸš¨ Critical Fix for Discovery
  
  # Service Discovery
  DISCOVERY_HOST: "discovery-service"
  
  # Database Hosts (Matching Service Names below)
  AUTH_DB_HOST: "auth-db"
  AUTH_DB_NAME: "auth_db"
  CLAIM_DB_HOST: "claim-db"
  CLAIM_DB_NAME: "claim_db"