apiVersion: v1
kind: Secret
metadata:
  name: ucrmp-secrets
  namespace: ucrmp-dev
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk
  jwt-secret: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==