apiVersion: v1
kind: ConfigMap
metadata:
  name: ucrmp-config
  namespace: {{ .Values.namespace }}
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_APPLICATION_JSON: '{"eureka": {"instance": {"prefer-ip-address": true}}}'
  DISCOVERY_HOST: "discovery-service"
  AUTH_DB_HOST: "auth-db"
  AUTH_DB_NAME: "auth_db"
  CLAIM_DB_HOST: "claim-db"
  CLAIM_DB_NAME: "claim_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: ucrmp-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlRoot }}
  jwt-secret: {{ .Values.secrets.jwt }}